# 服务器配置
server: 
  port: ":18080"  # 服务监听端口

# 数据库配置
database: 
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  dbName: blog_demo
  maxOpenConns: 100     # 最大打开连接数
  maxIdleConns: 20      # 最大空闲连接数
  connMaxLifetime: 30m  # 连接最大生命周期

# JWT 配置
jwt: 
  secretKey: "dgdDFGDGow235!~.gD34nlk&GD*Dsdoin3j4l5"  # 签名密钥
  expirationTime: 24h  # 令牌有效期（支持 h/m/s 单位）

logLevel: "info"  # 日志级别